# Generated by Django 3.2.19 on 2023-06-06 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWebsiteRecreationDatabase', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='image_link',
            new_name='logo_local_filepath',
        ),
        migrations.AddField(
            model_name='resource',
            name='logo_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
