# Generated by Django 3.2.18 on 2023-05-24 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('about_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_link', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Image_List',
            fields=[
                ('image_list_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('paragraph_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Paragraph_List',
            fields=[
                ('paragraph_list_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('resource_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('link', models.CharField(max_length=255)),
                ('image_link', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Resource_List',
            fields=[
                ('resource_list_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Video_List',
            fields=[
                ('video_list_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Video_Bridge',
            fields=[
                ('video_bridge_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MyWebsiteRecreationDatabase.video')),
                ('video_list_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MyWebsiteRecreationDatabase.video_list')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('resume_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('resource_list_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MyWebsiteRecreationDatabase.resource_list')),
            ],
        ),
        migrations.CreateModel(
            name='Resource_Bridge',
            fields=[
                ('resource_bridge_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MyWebsiteRecreationDatabase.resource')),
                ('resource_list_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MyWebsiteRecreationDatabase.resource_list')),
            ],
        ),
        migrations.CreateModel(
            name='Paragraph_Bridge',
            fields=[
                ('paragraph_bridge_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('page_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MyWebsiteRecreationDatabase.paragraph')),
                ('paragraph_list_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MyWebsiteRecreationDatabase.paragraph_list')),
            ],
        ),
        migrations.CreateModel(
            name='Image_Bridge',
            fields=[
                ('image_bridge_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MyWebsiteRecreationDatabase.image')),
                ('image_list_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MyWebsiteRecreationDatabase.image_list')),
            ],
        ),
        migrations.CreateModel(
            name='Footer_Information',
            fields=[
                ('footer_information_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('resource_list_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MyWebsiteRecreationDatabase.resource_list')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('date_last_update', models.DateField(auto_created=True)),
                ('article_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('image_preview', models.CharField(max_length=255)),
                ('max_order', models.IntegerField()),
                ('date_created', models.DateField()),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MyWebsiteRecreationDatabase.category')),
                ('image_list_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MyWebsiteRecreationDatabase.image_list')),
                ('paragraph_list_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MyWebsiteRecreationDatabase.paragraph_list')),
                ('resource_list_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MyWebsiteRecreationDatabase.resource_list')),
                ('video_lits_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='MyWebsiteRecreationDatabase.video_list')),
            ],
        ),
    ]
