# Generated by Django 3.2.18 on 2023-05-24 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyWebsiteRecreationDatabase', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paragraph_bridge',
            old_name='page_id',
            new_name='paragraph_id',
        ),
    ]
