# Generated by Django 3.2.18 on 2023-05-24 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyWebsiteRecreationDatabase', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page_list',
            old_name='rage_list_id',
            new_name='page_list_id',
        ),
    ]
