# Generated by Django 3.2.18 on 2023-04-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWebsiteRecreationDatabase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page_Context',
            fields=[
                ('page_context_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
