# Generated by Django 3.2.18 on 2023-05-23 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWebsiteRecreationDatabase', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image_list',
            old_name='resource_list_id',
            new_name='image_list_id',
        ),
        migrations.RenameField(
            model_name='video_list',
            old_name='resource_list_id',
            new_name='video_list_id',
        ),
        migrations.AlterField(
            model_name='resource',
            name='image_link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
