# Generated by Django 3.2.18 on 2023-04-21 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyWebsiteRecreationDatabase', '0002_page_context'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('page_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph', models.TextField()),
                ('image_file', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('resource_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Resource_List',
            fields=[
                ('resource_list_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_context_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MyWebsiteRecreationDatabase.page_context')),
                ('resource_id', models.ManyToManyField(to='MyWebsiteRecreationDatabase.Resource')),
            ],
        ),
        migrations.CreateModel(
            name='Page_list',
            fields=[
                ('page_list_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_context_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MyWebsiteRecreationDatabase.page_context')),
                ('page_id', models.ManyToManyField(to='MyWebsiteRecreationDatabase.Page')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('image_preview', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField()),
                ('date_last_update', models.DateTimeField()),
                ('Page_Context_id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='MyWebsiteRecreationDatabase.page_context')),
                ('category_id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='MyWebsiteRecreationDatabase.category')),
            ],
        ),
    ]
