# Generated by Django 3.2.18 on 2023-05-24 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyWebsiteRecreationDatabase', '0002_rename_rage_list_id_page_list_page_list_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='video_lits_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='MyWebsiteRecreationDatabase.video_list'),
        ),
    ]
