# Generated by Django 3.2.18 on 2023-05-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWebsiteRecreationDatabase', '0003_alter_article_video_lits_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
