# Generated by Django 3.2.18 on 2023-04-21 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWebsiteRecreationDatabase', '0004_alter_article_date_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_created',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='date_last_update',
            field=models.DateField(auto_created=True),
        ),
    ]
