# Generated by Django 3.2.18 on 2023-04-21 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWebsiteRecreationDatabase', '0005_auto_20230421_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
